Paul/docs
mystic-ai/pipeline pull request #69
Opened 2022-03-24 16:31 UTC by paulcjh

2022-03-24 16:46 UTC, bjornaer requested changes
could you pull main branch to sort out any conflicts if there are any?

2022-03-24 16:46 UTC, bjornaer commented on .github/workflows/publish-docs.yml
> +      - paul/docs
I guess you might want to change target branch?

2022-03-24 16:46 UTC, bjornaer commented on .gitignore
> +.DS_Store
Good man!

2022-03-25 15:16 UTC, bjornaer commented
> @bjornaer This is a draft branch atm

did not notice, I got pinged by github and reviewed haha nw

2022-03-25 15:29 UTC, paulcjh commented
> > @bjornaer This is a draft branch atm
> 
> did not notice, I got pinged by github and reviewed haha nw

Nw!

2022-11-30 03:36 UTC, closed without merging